repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.9.0-1
  hooks:
  - id: shfmt
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.6
  hooks:
  - id: ruff
    args: [ --fix ]
  - id: ruff-format
# Following recommendations from https://github.com/python/mypy/issues/13916
# This does make the mypy step slower
- repo: local
  hooks:
  - id: mypy
    name: mypy
    language: system
    entry: mypy
    types_or: [python, pyi]
    args: ["--strict", ""]
    pass_filenames: false
